# Generated by Django 6.0.7 on 2026-07-20 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('tipo_descuento', models.CharField(choices=[('Porcentaje', 'Porcentaje'), ('Monto fijo', 'Monto fijo')], max_length=15)),
                ('valor_descuento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='oferta', to='productos.producto')),
            ],
            options={
                'db_table': 'ofertas',
            },
        ),
    ]
