# Generated by Django 6.0.7 on 2026-07-20 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comercios', '0002_initial'),
        ('productos', '0001_initial'),
        ('reservas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='usuarios.cliente'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='comercio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='comercios.comercio'),
        ),
        migrations.AddField(
            model_name='reservaitem',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_reserva', to='productos.producto'),
        ),
        migrations.AddField(
            model_name='reservaitem',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reservas.reserva'),
        ),
    ]
