# Generated by Django 6.0.7 on 2026-07-20 03:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comercio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'El RUC debe tener exactamente 11 dígitos numéricos.')])),
                ('nombre_comercio', models.CharField(max_length=150, unique=True)),
                ('telefono_comercio', models.CharField(blank=True, default='', max_length=15)),
                ('direccion_comercio', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Suspendido', 'Suspendido')], default='Activo', max_length=15)),
            ],
            options={
                'db_table': 'comercios',
            },
        ),
    ]
